image: hashicorp/terraform:full

pipelines:
    pull-requests:
        '**':
            - step:
                name: Validate and output plan
                script:
                    - terraform init -input=false -backend-config="access_key=$AWS_ACCESS" -backend-config="secret_key=$AWS_SECRET"
                    - terraform validate
                    - terraform plan -out=tfplan -input=false
    branches:
        master:
            - step:
                name: Apply plan
                deployment: production
                script:
                    - terraform init -input=false -backend-config="access_key=$AWS_ACCESS" -backend-config="secret_key=$AWS_SECRET"
                    - terraform validate
                    - terraform plan -out=tfplan -input=false
                    - terraform apply -input=false -auto-approve tfplan